{{ config(materialized='view') }}

WITH CUSTOMERORDERS AS(
  SELECT
    c.CUSTOMERID,
    CONCAT(c.FIRSTNAME," ",c.LASTNAME) AS CUSTOMER_NAME,
    COUNT(*) AS NO_OF_ORDERS
  FROM L1_LANDING.CUSTOMERS c
  JOIN L1_LANDING.ORDERS o
  ON c.CUSTOMERID=o.CUSTOMERID
  GROUP BY c.CUSTOMERID, CUSTOMER_NAME
  ORDER BY NO_OF_ORDERS DESC
)
SELECT * FROM CUSTOMERORDERS